const RoadmapActionTypes = {
    ROADMAP_START: 'ROADMAP_START',
    ROADMAP_SUCCESS: 'ROADMAP_SUCCESS',
    ROADMAP_FAIL: 'ROADMAP_FAIL',

    FETCH_ALL_ROADMAP: 'FETCH_ALL_ROADMAP',
    FETCH_ROADMAP_BY_USER: 'FETCH_ROADMAP_BY_USER',
    FETCH_SINGLE_ROADMAP: 'FETCH_SINGLE_ROADMAP',

    FETCH_MOST_POPULAR_ROADMAPS: 'FETCH_MOST_POPULAR_ROADMAPS',
    FETCH_MOST_POPULAR_ROADMAPS_FAIL: 'FETCH_MOST_POPULAR_ROADMAPS_FAIL',
    FETCH_HIGHEST_RATED_ROADMAPS: 'FETCH_HIGHEST_RATED_ROADMAPS',
    FETCH_HIGHEST_RATED_ROADMAPS_FAIL: 'FETCH_HIGHEST_RATED_ROADMAPS_FAIL',

    SEARCH_ROADMAPS_SUCCESS: 'SEARCH_ROADMAPS_SUCCESS',
    SEARCH_ROADMAPS_FAIL: 'SEARCH_ROADMAPS_FAIL'
}

export default RoadmapActionTypes;
