const RoadmapActionTypes = {
    FETCH_ROADMAPS_REQUESTED: 'FETCH_ROADMAP_REQUESTED',

    FETCH_ALL_ROADMAP_START: 'FETCH_ALL_ROADMAP',
    FETCH_ALL_ROADMAP_SUCCESS: 'FETCH_ALL_ROADMAP_SUCCESS',
    FETCH_ALL_ROADMAP_FAIL: 'FETCH_ALL_ROADMAP_FAIL',

    FETCH_ROADMAP_BY_USER_START: 'FETCH_ROADMAP_BY_USER_START',
    FETCH_ROADMAP_BY_USER_SUCCESS: 'FETCH_ROADMAP_BY_USER_SUCCESS',
    FETCH_ROADMAP_BY_USER_FAIL: 'FETCH_ROADMAP_BY_USER_FAIL',

    FETCH_MOST_POPULAR_ROADMAPS_START: 'FETCH_MOST_POPULAR_ROADMAPS_START',
    FETCH_MOST_POPULAR_ROADMAPS_SUCCESS: 'FETCH_MOST_POPULAR_ROADMAPS_SUCCESS',
    FETCH_MOST_POPULAR_ROADMAPS_FAIL: 'FETCH_MOST_POPULAR_ROADMAPS_FAIL',

    FETCH_HIGHEST_RATED_ROADMAPS_START: 'FETCH_HIGHEST_RATED_ROADMAPS_START',
    FETCH_HIGHEST_RATED_ROADMAPS_SUCCESS: 'FETCH_HIGHEST_RATED_ROADMAPS_SUCCESS',
    FETCH_HIGHEST_RATED_ROADMAPS_FAIL: 'FETCH_HIGHEST_RATED_ROADMAPS_FAIL',

    SEARCH_ROADMAPS_START: 'SEARCH_ROADMAPS_START',
    SEARCH_ROADMAPS_SUCCESS: 'SEARCH_ROADMAPS_SUCCESS',
    SEARCH_ROADMAPS_FAIL: 'SEARCH_ROADMAPS_FAIL'
}

export default RoadmapActionTypes;
