export const ROADMAP_START = 'ROADMAP_START';
export const ROADMAP_SUCCESS = 'ROADMAP_SUCCESS';
export const ROADMAP_FAIL = 'ROADMAP_FAIL';

export const FETCH_ALL_ROADMAP = 'FETCH_ALL_ROADMAP';
export const FETCH_ROADMAP_BY_USER = 'FETCH_ROADMAP_BY_USER';
export const FETCH_SINGLE_ROADMAP = 'FETCH_SINGLE_ROADMAP';

export const FETCH_MOST_POPULAR_ROADMAPS = 'FETCH_MOST_POPULAR_ROADMAPS'
export const FETCH_MOST_POPULAR_ROADMAPS_FAIL = 'FETCH_MOST_POPULAR_ROADMAPS_FAIL'
export const FETCH_HIGHEST_RATED_ROADMAPS = 'FETCH_HIGHEST_RATED_ROADMAPS'
export const FETCH_HIGHEST_RATED_ROADMAPS_FAIL = 'FETCH_HIGHEST_RATED_ROADMAPS_FAIL'

export const SEARCH_ROADMAPS_SUCCESS = 'SEARCH_ROADMAPS_SUCCESS'
export const SEARCH_ROADMAPS_FAIL = 'SEARCH_ROADMAPS_FAIL'