# Generated by Django 3.0.7 on 2020-07-17 07:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import studyroadmap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('profile_image', models.CharField(default='', max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('credential', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinkStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advance')], default=0)),
                ('discipline', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business'), ('FINANCE', 'Finance'), ('SPORTS', 'Sports'), ('LIFE_HACK', 'Life Hack'), ('CULINARY', 'Culinary'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('OTHER', 'Other')], default=studyroadmap.models.DisciplineEnum['OTHER'], max_length=50)),
                ('num_shares', models.IntegerField(default=0)),
                ('num_views', models.IntegerField(default=0)),
                ('num_votes', models.IntegerField(default=0)),
                ('num_milestones', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studyroadmap.CustomProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now=True)),
                ('user_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='studyroadmap.CustomProfile')),
                ('user_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='studyroadmap.CustomProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.CustomProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('order_num', models.IntegerField()),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
