const DisciplineActionTypes = {
    FETCH_ALL_DISCIPLINE_START: 'FETCH_ALL_DISCIPLINE_START',
    FETCH_ALL_DISCIPLINE_SUCCESS: 'FETCH_ALL_DISCIPLINE_SUCCESS',
    FETCH_ALL_DISCIPLINE_FAIL: 'FETCH_ALL_DISCIPLINE_FAIL',
}

export default DisciplineActionTypes;

