# Generated by Django 3.0.6 on 2020-05-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('profile_image', models.CharField(max_length=100)),
                ('user_latitude', models.IntegerField()),
                ('user_longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('num_shares', models.IntegerField()),
                ('num_views', models.IntegerField()),
                ('num_votes', models.IntegerField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studyroadmap.User')),
            ],
        ),
    ]
