# Generated by Django 3.0.6 on 2020-05-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkStat',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='roadmap',
            old_name='user_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advance')], default=0),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='studyroadmap.User')),
                ('user_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='studyroadmap.User')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
            ],
        ),
    ]
