# Generated by Django 3.0.6 on 2020-05-30 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyroadmap', '0002_auto_20200527_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.IntegerField(choices=[(0, 'ENGINEERING'), (1, 'BUSINESS'), (2, 'FINANCE'), (3, 'SPORTS'), (4, 'LIFE_HACK'), (5, 'CULINARY'), (6, 'ENTREPRENEURSHIP'), (7, 'EDUCATION'), (8, 'HEALTH'), (9, 'OTHER')], default=9)),
                ('num_roadmaps', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='displine',
            field=models.IntegerField(choices=[(0, 'Engineering'), (1, 'Business'), (2, 'Finance'), (3, 'Sports'), (4, 'Life Hack'), (5, 'Culinary'), (6, 'Entrepreneurship'), (7, 'Education'), (8, 'Health'), (9, 'Other')], default=9),
        ),
        migrations.CreateModel(
            name='RoadmapFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
