# Generated by Django 3.0.6 on 2020-05-31 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0004_auto_20200530_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('order_num', models.IntegerField()),
                ('roadmap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroadmap.Roadmap')),
            ],
        ),
        migrations.DeleteModel(
            name='RoadmapNode',
        ),
    ]
