# Generated by Django 3.0.6 on 2020-05-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0004_auto_20200520_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='follow_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='linkstat',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadmapnode',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
