# Generated by Django 3.0.6 on 2020-05-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0005_auto_20200531_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='credential',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='profile_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='linkstat',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='roadmapstep',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
