# Generated by Django 3.0.6 on 2020-05-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0006_auto_20200531_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='discipline',
            field=models.IntegerField(choices=[(0, 'ENGINEERING'), (1, 'BUSINESS'), (2, 'FINANCE'), (3, 'SPORTS'), (4, 'LIFE_HACK'), (5, 'CULINARY'), (6, 'ENTREPRENEURSHIP'), (7, 'EDUCATION'), (8, 'HEALTH'), (9, 'OTHER')], default=9, unique=True),
        ),
    ]
