# Generated by Django 3.0.6 on 2020-05-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0007_auto_20200531_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
