# Generated by Django 3.0.6 on 2020-05-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0008_delete_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='discipline',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Business', 'Business'), ('Finance', 'Finance'), ('Sports', 'Sports'), ('Life Hack', 'Life Hack'), ('Culinary', 'Culinary'), ('Entrepreneurship', 'Entrepreneurship'), ('Education', 'Education'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
