# Generated by Django 3.0.6 on 2020-05-31 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0009_auto_20200531_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('Engineering', 'Engineering'), ('Business', 'Business'), ('Finance', 'Finance'), ('Sports', 'Sports'), ('Life Hack', 'Life Hack'), ('Culinary', 'Culinary'), ('Entrepreneurship', 'Entrepreneurship'), ('Education', 'Education'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=20, unique=True)),
                ('num_roadmaps', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studyroadmap.Discipline'),
        ),
    ]
