# Generated by Django 3.0.6 on 2020-05-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0010_auto_20200531_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discipline',
            field=models.IntegerField(choices=[(0, 'ENGINEERING'), (1, 'BUSINESS'), (2, 'FINANCE'), (3, 'SPORTS'), (4, 'LIFE_HACK'), (5, 'CULINARY'), (6, 'ENTREPRENEURSHIP'), (7, 'EDUCATION'), (8, 'HEALTH'), (9, 'OTHER')], default=9, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='discipline',
            field=models.IntegerField(choices=[(0, 'Engineering'), (1, 'Business'), (2, 'Finance'), (3, 'Sports'), (4, 'Life Hack'), (5, 'Culinary'), (6, 'Entrepreneurship'), (7, 'Education'), (8, 'Health'), (9, 'Other')], default=9),
        ),
    ]
