# Generated by Django 3.0.6 on 2020-05-31 23:13

from django.db import migrations, models
import studyroadmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0012_auto_20200531_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='discipline',
            field=models.CharField(choices=[(studyroadmap.models.DisciplineEnum['ENGINEERING'], 'Engineering'), (studyroadmap.models.DisciplineEnum['BUSINESS'], 'Business'), (studyroadmap.models.DisciplineEnum['FINANCE'], 'Finance'), (studyroadmap.models.DisciplineEnum['SPORTS'], 'Sports'), (studyroadmap.models.DisciplineEnum['LIFE_HACK'], 'Life Hack'), (studyroadmap.models.DisciplineEnum['CULINARY'], 'Culinary'), (studyroadmap.models.DisciplineEnum['ENTREPRENEURSHIP'], 'Entrepreneurship'), (studyroadmap.models.DisciplineEnum['EDUCATION'], 'Education'), (studyroadmap.models.DisciplineEnum['HEALTH'], 'Health'), (studyroadmap.models.DisciplineEnum['OTHER'], 'Other')], default=studyroadmap.models.DisciplineEnum['OTHER'], max_length=50),
        ),
    ]
