# Generated by Django 3.0.6 on 2020-05-31 23:16

from django.db import migrations, models
import studyroadmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0013_auto_20200531_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='discipline',
            field=models.CharField(choices=[('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business'), ('FINANCE', 'Finance'), ('SPORTS', 'Sports'), ('LIFE_HACK', 'Life Hack'), ('CULINARY', 'Culinary'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('OTHER', 'Other')], default=studyroadmap.models.DisciplineEnum['OTHER'], max_length=50),
        ),
    ]
