# Generated by Django 3.0.6 on 2020-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroadmap', '0014_auto_20200531_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadmapStep',
            new_name='Milestone',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='num_milestones',
            field=models.IntegerField(default=0),
        ),
    ]
